CREATE VIEW empresa_dica AS SELECT * FROM empresa emp INNER JOIN usuario_empresa_link uel  on uel.emp_id_link = emp.emp_id inner join usuario u  on  uel.user_id_link = u.user_id inner join post p  on  u.user_id = p.userpost_id INNER JOIN categoria c  on c.cat_id = p.postcat_id INNER JOIN dica d  on  p.post_id = d.postdic_id ;
CREATE VIEW empresa_vincula_prova AS select* from post p left join vaga v on p.post_id = v.postvaga_id left join vaga_prova_link link on link.linkvag_id = v.vag_id left join prova pro on pro.pro_id = link.linkpro_id;
CREATE VIEW pedido_mensagems AS SELECT * FROM pedido p inner join pedido_mensagem_link pml on  pml.pml_pedi_id = p.pedi_id inner join mensagem m  on m.msn_id = pml.pml_msn_id;
CREATE VIEW pedido_conversas AS select * from pedido p join pedido_mensagem_link pml on  pml.pml_pedi_id = p.pedi_id  join mensagem m  on m.msn_id = pml.pml_msn_id  join servico serv on  serv.serv_id = p.pedi_serv_id  join post po on  po.post_id = serv.postserv_id  join usuario u on  u.user_id = p.cliente_user_id or p.pedi_prestador_user_id = u.user_id ;
CREATE VIEW empresa_pedido_plano as select * from  empresa emp left join pedidoplano pd  on emp.emp_id = pd.pd_emp_id inner join status_payments st  on  st.statuspay_id = pd.pd_payments_id;
CREate view vaga_conversas as SELECT * FROM mensagem m inner join vaga_mensagem_link vml on m.msn_id = vml.vml_msn_id inner join vaga v on v.vag_id = vml.vml_vaga_id inner join post p on p.post_id = v.postvaga_id inner join vaga_mensagem_dados_link vmdl on vml.vmdl_id = vmdl.vmdl_idd;
create view usuario_servico AS select * from servico s inner join post p on p.post_id = s.postserv_id inner join usuario us on p.userpost_id =us.user_id inner join categoria c on c.cat_id = p.postcat_id inner join status_servico stav on stav.statServ_id = s.statusServ_id inner join endereco ender on ender.ender_id = p.post_ender_id inner join estado est on ender.enderest_id = est.est_id;
create view candidato_explore AS select * from vaga v inner join post p on  p.post_id = v.postvaga_id inner join usuario us  on  p.userpost_id =us.user_id inner join categoria c  on  c.cat_id = p.postcat_id inner join status_vaga stavaga on  stavaga.statusvag_id = v.vagstatus_id inner join tipo_vaga tivaga  on  tivaga.tipovaga_id = v.tivaga_id  inner join endereco ender on  ender.ender_id = p.post_ender_id inner join estado est on  ender.enderest_id = est.est_id;
CREATE VIEW empresa_prova AS select * from empresa e join prova p on e.emp_id = p.proemp_id;
CREATE VIEW empresa_prestador_pedidos AS select * from empresa emp INNER JOIN usuario_empresa_link uel on  emp.emp_id = uel.emp_id_link inner join usuario u on  uel.user_id_link = u.user_id INNER JOIN pedido_prestador pedipre on  u.user_id = pedipre.prestador_user_id join pedido pe on  pedipre.prestador_pedi_id = pe.pedi_id;
CREATE VIEW escolaridade_post_vaga AS select * from post p join vaga v on v.postvaga_id = p.post_id join escolaridade e on e.esco_id = v.vagesco_id;
CREATE VIEW post_dica AS select * from ((post p join categoria c on (c.cat_id = p.postcat_id)) join dica d on (p.post_id = d.postdic_id));
CREATE VIEW duvidas_categorias_view  AS  SELECT * FROM duvidas duv join duvidas_categoria dv on  duv.duvcategoria_id = dv.duvcat_id;
CREATE VIEW usuario_post_servico AS SELECT* FROM usuario u INNER JOIN post p on u.user_id = p.userpost_id INNER JOIN categoria c on c.cat_id = p.postcat_id INNER JOIN servico s on p.post_id = s.postserv_id INNER JOIN status_servico staserv on staserv.statServ_id = s.statusServ_id INNER JOIN endereco ender on ender.ender_id = p.post_ender_id INNER JOIN estado est on ender.enderest_id = est.est_id;
CREATE VIEW empresa_servico AS SELECT * FROM empresa emp INNER JOIN usuario_empresa_link uel on uel.emp_id_link = emp.emp_id inner join usuario u on uel.user_id_link = u.user_id inner join post p on u.user_id = p.userpost_id INNER JOIN categoria c on c.cat_id = p.postcat_id INNER JOIN servico s on p.post_id = s.postserv_id INNER JOIN status_servico staserv on staserv.statServ_id = s.statusServ_id INNER JOIN endereco ender on ender.ender_id = p.post_ender_id INNER JOIN estado est on ender.enderest_id = est.est_id;
CREATE VIEW post_vaga AS SELECT* FROM empresa emp INNER JOIN usuario_empresa_link uel on uel.emp_id_link = emp.emp_id inner join usuario u on uel.user_id_link = u.user_id INNER JOIN post p on p.userpost_id = u.user_id INNER JOIN categoria c on c.cat_id = p.postcat_id INNER JOIN vaga v on p.post_id = v.postvaga_id INNER JOIN status_vaga stavaga on stavaga.statusvag_id = v.vagstatus_id INNER JOIN tipo_vaga tivaga on tivaga.tipovaga_id = v.tivaga_id left JOIN escolaridade esco on esco.esco_id - v.vagesco_id INNER JOIN endereco ender on ender.ender_id = p.post_ender_id INNER JOIN estado est on ender.enderest_id = est.est_id;
CREATE VIEW empresa_vaga AS SELECT* FROM empresa emp left JOIN usuario_empresa_link uel on uel.emp_id_link = emp.emp_id left join usuario u on uel.user_id_link = u.user_id LEFT JOIN post p on u.user_id = p.userpost_id LEFT JOIN categoria c on c.cat_id = p.postcat_id LEFT JOIN vaga v on p.post_id = v.postvaga_id LEFT JOIN status_vaga stavaga on stavaga.statusvag_id = v.vagstatus_id JOIN tipo_vaga tivaga on tivaga.tipovaga_id = v.tivaga_id LEFT JOIN escolaridade esco on esco.esco_id = v.vagesco_id LEFT JOIN endereco ender on ender.ender_id = p.post_ender_id LEFT JOIN estado est on ender.enderest_id = est.est_id;
CREATE VIEW empresa_conta AS SELECT* FROM empresa emp INNER JOIN usuario_empresa_link uel on uel.emp_id_link = emp.emp_id inner join usuario u on uel.user_id_link = u.user_id INNER JOIN conta_bancaria c on c.cont_user_id = u.user_id INNER JOIN conta_bancos cb on cb.bank_id = c.cont_bank_id;
CREATE VIEW candidato_conta AS SELECT* FROM candidato cand INNER JOIN usuario USER on cand.canduser_id = USER.user_id INNER JOIN conta_bancaria cont on cont.cont_user_id = USER.user_id INNER JOIN conta_bancos cb  on cb.bank_id = cont.cont_bank_id; 
CREATE VIEW candidato_pedidos AS SELECT* FROM candidato cand INNER JOIN usuario USER on cand.canduser_id = USER.user_id INNER JOIN pedido pedi on pedi.cliente_user_id = USER.user_id INNER JOIN servico serv on pedi.pedi_serv_id = serv.serv_id INNER JOIN post po on po.post_id = serv.postserv_id INNER JOIN status_pedido stpe on stpe.statuspedi_id = pedi.statuspe_id;
CREATE VIEW empresa_pedidos AS SELECT* FROM empresa emp INNER JOIN usuario_empresa_link uel on emp.emp_id = uel.emp_id_link inner join usuario u on uel.user_id_link = u.user_id INNER JOIN pedido pedi on pedi.cliente_user_id = u.user_id INNER JOIN servico serv on pedi.pedi_serv_id = serv.serv_id INNER JOIN post po on po.post_id = serv.postserv_id INNER JOIN status_pedido stpe on stpe.statuspedi_id = pedi.statuspe_id;
CREATE VIEW candidato_prestador_pedidos AS SELECT* FROM candidato ca INNER JOIN usuario u on ca.canduser_id = u.user_id INNER JOIN pedido_prestador pedipre on u.user_id = pedipre.prestador_user_id INNER JOIN pedido pe on pedipre.prestador_pedi_id = pe.pedi_prestador_user_id;
CREATE VIEW pedido_detalhes AS SELECT *FROM post p INNER JOIN endereco ender on p.post_ender_id = ender.ender_id INNER JOIN servico serv on p.post_id = serv.postserv_id INNER JOIN pedido pe on pe.pedi_serv_id = serv.serv_id INNER JOIN status_progress stpro on stpro.statusnumber_id = pe.status_number_id INNER JOIN status_pedido stpe on stpe.statuspedi_id = pe.statuspe_id;
CREATE VIEW pedidos_prestador_dados AS SELECT*FROM usuario u INNER JOIN pedido_prestador pedipre on u.user_id = pedipre.prestador_user_id INNER JOIN pedido pe on pedipre.prestador_pedi_id = pe.pedi_id INNER JOIN servico serv on serv.serv_id = pe.pedi_prestador_user_id;
CREATE VIEW empresa_solicitacoes AS SELECT*FROM empresa emp INNER JOIN usuario_empresa_link uel on emp.emp_id =uel.emp_id_link inner join usuario u on u.user_id = uel.user_id_link INNER JOIN solicitacoes soli on soli.soli_id = u.user_id INNER JOIN status_solicitacao statussoli on statussoli.status_soli_id = soli.soli_id INNER JOIN solicitacao_categoria solicat on solicat.solicat_id = soli.soli_id;
CREATE VIEW blog_post_categoria AS SELECT* FROM blog b INNER JOIN blog_categoria cat on b.blog_categoria_id = cat.blogcat_id INNER JOIN blog_destaque bd on b.blogdestaque_id = bd.blogdest_id;;
CREATE VIEW post_vaga_prova AS SELECT* FROM post p INNER JOIN vaga vg ON  p.post_id = vg.postvaga_id INNER JOIN vaga_prova_link vpl  ON vpl.linkvag_id = vg.vag_id INNER JOIN prova pv  ON pv.pro_id = vpl.linkpro_id;
CREATE VIEW empresa_prova_pergunta AS SELECT*FROM prova p INNER JOIN questionario q on  p.pro_id = q.questpro_id;
CREATE VIEW empresa_quiz_pergunta AS SELECT*FROM prova p INNER JOIN quiz on p.pro_id = quiz.quizpro_id;
CREATE VIEW candidato_dados AS SELECT*FROM usuario u INNER JOIN candidato c on c.canduser_id = u.user_id INNER JOIN endereco ender on ender.ender_id = u.user_ender_id INNER JOIN estado est on est.est_id = ender.enderest_id LEFT JOIN fichaexperiecia fe on c.cand_id = fe.candidato_id ;
CREATE VIEW candidato_servico AS SELECT*FROM candidato c INNER JOIN usuario u on c.canduser_id = u.user_id INNER JOIN post p on u.user_id = p.userpost_id INNER JOIN categoria cat on  cat.cat_id = p.postcat_id INNER JOIN servico s on p.post_id = s.postserv_id INNER JOIN status_servico staserv on staserv.statServ_id = s.statusServ_id INNER JOIN endereco ender on  ender.ender_id = p.post_ender_id INNER JOIN estado est on ender.enderest_id = est.est_id;
CREATE VIEW usuario_explore_servico AS SELECT*FROM usuario u INNER JOIN post p on u.user_id = p.userpost_id INNER JOIN categoria cat on cat.cat_id = p.postcat_id INNER JOIN servico s on p.post_id = s.postserv_id INNER JOIN status_servico staserv  on staserv.statServ_id = s.statusServ_id INNER JOIN endereco ender on  ender.ender_id = p.post_ender_id INNER JOIN estado est on  ender.enderest_id = est.est_id;
CREATE VIEW competencias_categorias AS SELECT*FROM competencias c INNER JOIN competencia_categoria cc on  c.compcate_id = cc.compcat_id;
CREATE VIEW competencia_vagas AS SELECT*FROM vaga vag INNER JOIN competencia_vaga_link cvl on vag.vag_id = cvl.linkvag_id INNER JOIN competencias comp  on comp.comp_id = cvl.linkcomp_id INNER JOIN competencia_categoria cc  on cc.compcat_id = comp.compcate_id;
CREATE VIEW competencia_candidato AS SELECT* FROM vaga vag INNER JOIN competencia_vaga_link cvl on  vag.vag_id = cvl.linkvag_id INNER JOIN competencias comp on  comp.comp_id = cvl.linkcomp_id INNER JOIN competencia_categoria cc  on cc.compcat_id = comp.compcate_id;
CREATE VIEW candidato_prova_resposta AS SELECT * FROM vaga v INNER JOIN vaga_prova_link vpl on v.vag_id = vpl.linkvag_id INNER JOIN prova pr on vpl.linkpro_id = pr.pro_id INNER JOIN questionario q  on pr.pro_id = q.questpro_id LEFT JOIN resposta resp on q.quest_id = resp.respquest_id LEFT JOIN candidato cand on cand.cand_id = resp.respcand_id;
CREATE VIEW candidato_quiz_resposta AS SELECT* FROM vaga v INNER JOIN vaga_prova_link vpl on  v.vag_id = vpl.linkvag_id INNER JOIN prova pr on  vpl.linkpro_id = pr.pro_id INNER JOIN quiz q on pr.pro_id = q.quizpro_id LEFT JOIN resposta_quiz respquiz on q.quiz_id = respquiz.requiz_id LEFT JOIN candidato cand on cand.cand_id = respquiz.requizcand_id;
CREATE VIEW empresa_candidato_ficha AS SELECT* FROM post p INNER JOIN vaga v on p.post_id = v.postvaga_id INNER JOIN candidato_vaga_link cvl on v.vag_id = cvl.cvlvag_id INNER JOIN candidato cand on cand.cand_id = cvl.cvlcand_id LEFT JOIN fichaexperiecia fe on fe.candidato_id = cand.cand_id
CREATE VIEW empresa_candidato_vaga AS SELECT * FROM post p INNER JOIN vaga v on  p.post_id = v.postvaga_id INNER JOIN candidato_vaga_link cvl on v.vag_id = cvl.cvlvag_id INNER JOIN candidato cand on cand.cand_id = cvl.cvlcand_id INNER JOIN usuario USER  on cand.canduser_id = USER.user_id INNER JOIN endereco ender on  ender.ender_id = USER.user_ender_id INNER JOIN estado est on est.est_id = ender.enderest_id;
CREATE VIEW usuario_perfil AS SELECT * FROM candidato c RIGHT JOIN usuario u on c.canduser_id = u.user_id LEFT JOIN usuario_empresa_link uel on u.user_id = uel.user_id_link left join empresa e on e.emp_id = uel.emp_id_link;
CREATE VIEW dados_usuario_post AS SELECT * FROM post p INNER JOIN categoria c on p.postcat_id = c.cat_id INNER JOIN tipo_post tp on tp.tipopost_id = p.tipo_post_id INNER JOIN usuario USER on p.userpost_id = USER.user_id;
CREATE VIEW dados_usuario_shere AS SELECT * FROM post p INNER JOIN categoria c on p.postcat_id = c.cat_id INNER JOIN tipo_post tp on tp.tipopost_id = p.tipo_post_id INNER JOIN shere sh on  sh.shere_post_id = p.post_id INNER JOIN usuario u on  u.user_id = sh.shere_user_id;
CREATE VIEW notifications_shere AS SELECT* FROM shere sh INNER JOIN tipo_post ti on ti.tipopost_id = sh.shere_ti_post INNER JOIN post p on p.post_id = sh.shere_post_id INNER JOIN categoria cat on cat.cat_id = p.postcat_id;
CREATE VIEW mysherepoint AS SELECT * FROM post p INNER JOIN categoria c on p.postcat_id = c.cat_id INNER JOIN tipo_post tp on tp.tipopost_id = p.tipo_post_id INNER JOIN endereco on endereco.ender_id = p.post_ender_id INNER JOIN estado est on est.est_id = endereco.enderest_id INNER JOIN shere sh on p.post_id = sh.shere_post_id INNER JOIN usuario USER on USER.user_id = sh.shere_user_id;
CREATE VIEW candidato_estadocivil AS SELECT * FROM candidato candc INNER JOIN estado_civil estc on candc.candestc_id = estc.estc_id;
CREATE VIEW notifications_candidatovaga AS SELECT * FROM candidato_vaga_link cvl INNER JOIN vaga v on cvl.cvlvag_id = v.vag_id INNER JOIN post p on v.postvaga_id = p.post_id INNER JOIN categoria cat on cat.cat_id = p.postcat_id;
CREATE VIEW notifications_servicos AS SELECT * FROM pedido p INNER JOIN usuario u on p.cliente_user_id = u.user_id; (logica)
CREATE VIEW notifications_mensagem_vaga AS SELECT * FROM vaga_mensagem_link vml INNER JOIN vaga v on vml.vml_vaga_id = v.vag_id INNER JOIN post p on v.postvaga_id = p.post_id;
CREATE VIEW empresa_dados AS SELECT * FROM empresa emp inner join usuario_empresa_link uel on  emp.emp_id = uel.emp_id_link inner join usuario u on   uel.user_id_link = u.user_id join endereco ender on   ender.ender_id = u.user_ender_id join estado est  on  est.est_id = ender.enderest_id;
CREATE view usuario_preferencias as SELECT * from usuario u inner join preferencias p on u.user_preferences_id = p.pref_id;
CREATE VIEW candidato_solicitacoes AS select * from candidato cand inner join usuario user on cand.canduser_id = user.user_id inner join solicitacoes soli on soli.soli_id = user.user_id inner join status_solicitacao statussoli on statussoli.status_soli_id = soli.soli_id inner join solicitacao_categoria solicat on solicat.solicat_id = soli.soli_id


notifications_candidatovaga